=== TheBong91/xml-blackjack/assets/xml/projfolder/main.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT casino (game*)>

<!ELEMENT game (card*,dealer,player+)>
<!ATTLIST game
id ID #REQUIRED
maxBet CDATA #REQUIRED
minBet CDATA #REQUIRED
activePlayer CDATA #REQUIRED>

<!ELEMENT player (card*)>
<!ATTLIST player
id ID #REQUIRED
bet CDATA #REQUIRED
balance CDATA #REQUIRED
name CDATA #REQUIRED
insurance CDATA #REQUIRED>

<!ELEMENT dealer (card*)>

<!ELEMENT card (#PCDATA)>
<!ATTLIST card
hidden CDATA #REQUIRED
color CDATA #REQUIRED
value CDATA #REQUIRED>

=== TheBong91/xml-blackjack/projfolder/instance5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE casino SYSTEM "main.dtd">
<casino>
    <game id="ID000" maxBet="1200" minBet="5" activePlayer="id_player_001">
        <!-- INSERT DECK HERE -->
        <dealer>
            <card hidden="false" color="diamond" value="6">
            </card>
            <card hidden="true" color="hearts" value="b">
            </card>
        </dealer>
        <player id="id_player_000" bet="10" balance="150" name="manuel" insurance="false">
            <card hidden="false" color="clubs" value="a">
            </card>
            <card hidden="false" color="spade" value="3">
            </card>
            <card hidden="false" color="diamond" value="5">
            </card>
        </player>
        <player id="id_player_001" bet="5" balance="150" name="michi" insurance="false">
            <card hidden="false" color="diamond" value="5">
            </card>
            <card hidden="false" color="clubs" value="7">
            </card>
        </player>
        <player id="id_player_002" bet="20" balance="150" name="robert" insurance="false">
            <card hidden="false" color="hearts" value="q">
            </card>
            <card hidden="false" color="clubs" value="a">
            </card>
        </player>
        <player id="id_player_003" bet="15" balance="150" name="anne" insurance="false">
            <card hidden="false" color="hearts" value="k">
            </card>
            <card hidden="false" color="spades" value="k">
            </card>
        </player>
        <player id="id_player_004" bet="10" balance="150" name="lenny" insurance="false">
            <card hidden="false" color="spades" value="3">
            </card>
            <card hidden="false" color="hearts" value="9">
            </card>
        </player>
    </game>
</casino>

<!-- Spieler id_player_000 hat "hit" ausgewÃ¤hlt und daraufhin "stand"
     Spieler id_player_001 ist nun an der Reihe und hat die "hit" oder "stand" Auswahl -->

=== TheBong91/xml-blackjack/projfolder/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE casino SYSTEM "main.dtd">
<casino>
    <game id="ID000" maxBet="1200" minBet="5" activePlayer="id_player000">  
        <!-- INSERT DECK HERE -->

        <dealer/>
        
        <player id="id_player_000" bet="0" balance="150" name="manuel" insurance="false">
        </player>
        <player id="id_player_001" bet="0" balance="150" name="michi" insurance="false">
        </player>
        <player id="id_player_002" bet="0" balance="150" name="robert" insurance="false">
        </player>
        <player id="id_player_003" bet="0" balance="150" name="anne" insurance="false">
        </player>
        <player id="id_player_004" bet="0" balance="150" name="lenny" insurance="false">
        </player>
    </game>
</casino>

<!-- Geld setzen vor dem Karten ausgeben -->
